const btnEl = document.getElementById("btn");
const mensagemEl = document.querySelector("p");

function getLove() {
  var mensagensAmor = [
    "Eu te amo mais do que tudo!",
    "Você é a pessoa mais especial da minha vida!",
    "Meu amor por você é infinito!",
    "Você é o meu raio de sol!",
    "Com você, meu coração é completo!","Se eu fosse um astronauta eu viajaria em todas os planetas até me encontrar com você de novo",
    "Se eu fosse uma abelha eu tomaria o pólen da sua flor todos os dias",
    "Se eu fosse um cachorro eu cheraria seu cu todo dia",
    "Se você fosse um peido eu nunca te soltaria",
    "Se você fosse cocô eu nunca daria descarga",
    "Se você é a mulher mais linda do mundo você seria exatamente a mulher que você é hoje e nada mudaria",
    "Se você fosse um prêmio da lotérica, eu compraria todos os bilhetes só pra ter você",
    "Se você fosse o sol e eu fosse a lua, eu esperaria ansiosamente todos os dias pelo nosso eclipse",
    "Se você fosse o mar eu queria ser a areia pra ter você comigo pra sempre",
    "Se eu fosse um peixe eu queria que você fosse o mar por que eu não vivo sem você",
    "Se você fosse uma planta, eu queria ser o solo pra ficar com você todos os dias",
    "Se eu fosse uma planta, com ctz vc seria o sol que me dá luz e vida e me ajuda a levantar todos os dias",
    "Apenas uma foto sua faria com que os anjos questionassem a própria perfeição",
     "Um dia você vai me perguntar o que é mais importante? Minha vida ou a sua? Eu direi a minha e você vai embora sem saber que você é minha vida",
    "Eu sempre gostei do universo, as estrelas e astronomia por que sempre achei lindo mas o dia em que olhei nos seus olhos eu percebi que a beleza de toda galáxia é insignificante perto da sua lindeza",
     "Se você morresse eu teria ciúmes da terra por ter você por perto pro resto da eternidade",
    "Se um dia eu me perder, eu vou procurar você, por que é em você que eu me encontro",
    "VOCE É LINDA",
    "EU TE AMO LINDA","VOCE É LINDA",
    "EU TE AMO","VOCE É LINDA",
    "EU TE AMO LINDA","VOCE É LINDA",
    "EU TE AMO BEM MUITÃO", "XODADI","XODADI","XODADI","XODADI","SEI LÁ","SEI LÁ","SEI LÁ","SEI LÁ",
    "Não há ninguém, mesmo sem cultura, que não se torne poeta quando o amor toma conta dele."
    ,"O que a memória ama, fica eterno. Te amo com a memória, imperecível.","Eu te amo para amar-te e não para ser amado, pois nada me dá tanta felicidade como te ver feliz.","QUERO CASAR SÓ PARA OLHAR NOS TEUS OLHOS TODOS OS DIAS DA MINHA VIDA","se van gogh olhasse a beleza que vejo em teus olhos amaria a vida como ninguém.(ele se matou)", "VOCE ACAB DE ENCONTRAR UMA MOPA, VOCE ESTA DEVENDO 50 BEIJINHOS", "VOCE ACABA DE ENCONTRAR UMA MOPA E ESTA DEVENDO UMA FOTO TEMPORARIA", "VOCE ACABDE ENCONTRAR UMA MOPA E ESTA DEVENDO UM ABRAÇO BEM APERTADO","Você é a luz que ilumina todos os meus dias.",
    "Meu amor por você é como um oceano infinito, profundo e cheio de ternura.",
    "Nosso amor é uma dança perfeita, onde nossos corações seguem o ritmo um do outro.",
    "Cada momento ao seu lado é um tesouro que guardo no meu coração.",
    "Seu sorriso é a minha fonte de felicidade e inspiração.",
    "Você transforma a simplicidade em magia, apenas com sua presença.",
    "O mundo ganha cores mais vibrantes quando estou nos seus braços.",
    "Em você, encontrei não apenas um amor verdadeiro, mas também minha melhor versão.",
    "Seu abraço é o meu refúgio seguro, onde encontro paz e calor.",
    "Seu sorriso é capaz de curar qualquer tristeza que exista em mim.",
    "Estar com você é como viver em um eterno conto de fadas, cheio de amor e encantamento.",
    "Você é o motivo pelo qual eu acordo todas as manhãs com um sorriso no rosto.",
    "Seu amor é um bálsamo que acalma todas as minhas dores e aflições.",
    "Meu coração bate no ritmo da sua presença, e cada batida é uma declaração de amor.",
    "Você é a razão pela qual eu acredito no poder do destino e no encontro de almas gêmeas.",
    "Seu amor é como uma chama eterna, que aquece meu coração mesmo nos dias mais frios.",
    "Com você ao meu lado, sinto que posso conquistar o mundo e enfrentar qualquer desafio.",
    "Seu sorriso é uma obra de arte que ilumina até mesmo os dias mais nublados.",
    "Nenhum poema ou canção seria capaz de descrever toda a profundidade do meu amor por você.",
    "Você é minha fortaleza, meu porto seguro, minha inspiração constante.",
    "Seu olhar é capaz de derreter meu coração e me fazer sentir único e especial.",
    "Estar ao seu lado é como mergulhar em um mar de felicidade e plenitude.",
    "Sua voz é a melodia perfeita que embala meus sonhos todas as noites.",
    "Em cada gesto seu, encontro uma prova concreta do amor puro e verdadeiro.",
    "Você é a essência de todos os meus sonhos e a realidade mais bonita que já vivi.",
    "Só de pensar em você, meu coração se enche de alegria e meu rosto se ilumina com um sorriso.",
    "Seu amor é um tesouro que eu valorizo mais do que qualquer riqueza material.",
    "Amar você é como respirar, é algo natural e indispensável para minha existência.",
    "Você é o presente mais precioso que a vida poderia me dar, e sou grato(a) todos os dias por tê-lo(a).",
    "Cada segundo ao seu lado é um pedacinho do paraíso que encontrei aqui na Terra.",
    "Seu amor é o combustível que me impulsiona a ser uma versão melhor de mim mesmo(a) a cada dia.",
    "Quando estou com você, o tempo parece parar, e apenas nosso amor preenche o espaço.",
    "Seu sorriso é uma canção suave que embala meus pensamentos e acalma minha alma.",
    "Amar você é como viver em um sonho do qual eu nunca quero acordar.",
    "Você é o motivo pelo qual minha vida ganhou um novo sentido e uma felicidade sem igual.",
    "Seu abraço é meu porto seguro, onde encontro paz, conforto e todo o amor que preciso.",
    "Quando olho nos seus olhos, encontro um universo inteiro de amor e compreensão.",
    "Você é a chave que abre as portas do meu coração, revelando um amor eterno e verdadeiro.",
    "Em cada gesto seu, encontro uma razão a mais para amar você incondicionalmente.",
    "Seu amor é como um farol, que me guia nas noites escuras e me mostra o caminho da felicidade.",
    "Você é a razão pela qual acredito na beleza do amor e no poder de cura que ele traz.",
    "Com você, descobri o verdadeiro significado da palavra felicidade e entendi como é amar intensamente.",
    "Você é a peça que faltava no quebra-cabeça da minha vida, completando-me de forma única e perfeita.",
    "Seu sorriso é como um raio de sol, iluminando meu mundo e trazendo calor ao meu coração.",
    "Você é o sonho que nunca desejo acordar, a realidade mais bonita que já vivi.",
    "Com você, cada dia é uma nova oportunidade de criar memórias incríveis e compartilhar um amor inabalável.",
    "Seu amor me dá asas para voar e a segurança de um porto seguro para sempre retornar.",
    "Você é a personificação do amor em sua forma mais pura e bela, e sou grato(a) por tê-lo(a) em minha vida.",
    "Com você, sinto que sou capaz de superar qualquer obstáculo e enfrentar qualquer tempestade que a vida possa trazer.",
    "Meu amor por você é eterno, infinito e imensurável, e sorrir ao seu lado é a maior alegria que já conheci.","SE A VIDA FOSSE UM FILME VOCE SERIA A MELHOR PARTE","Cause you're amazing just the way you are - Bruno Mars, Just the Way You Are",
    "I think I wanna marry you - Bruno Mars, Marry You",
    "You're the best thing I never knew I needed - Bruno Mars, Never Knew I Needed",
    "Cause, darling, I'm a nightmare dressed like a daydream- Taylor Swift, Blank Space",
    "You're beautiful, it's true - James Blunt, You're Beautiful",
    "You're the reason I come home - Ron Pope, A Drop in the Ocean",
    "When I see your face, there's not a thing that I would change - Bruno Mars, Just the Way You Are",
    "I'm yours, you're mine, you're what I've been waiting for - Jason Mraz, I'm Yours",
    "Cause all of me loves all of you - John Legend, All of Me",
    "You're still the one I run to, the one that I belong to - Shania Twain, You're Still the One",
    "You're the reason I believe in love - Daniel Caesar, Best Part",
    "And darling, I will be loving you 'til we're 70 - Ed Sheeran, Thinking Out Loud",
    "You're my sunshine on a rainy day - Bruno Mars, Count on Me",
    "You make me feel like I'm living a teenage dream - Katy Perry, Teenage Dream",
    "You're the closest to heaven that I'll ever be - The Goo Goo Dolls, Iris",
    "I wanna love you inside out - The Chainsmokers, Inside Out",
    "Cause all I need is a beauty and a beat - Justin Bieber ft. Nicki Minaj, Beauty and a Beat",
    "You are the best thing that's ever been mine - Taylor Swift, Mine",
    "When I see your smile, the whole world stops and stares for a while - Bruno Mars, Just the Way You Are",
    "You're my wonderwall - Oasis, Wonderwall",
    "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. - 1 Coríntios 13:4",
"Põe-me como selo sobre o teu coração, como selo sobre o teu braço; porque o amor é forte como a morte. - Cantares de Salomão 8:6",
"O marido conceda à esposa o que lhe é devido, e também, semelhantemente, a esposa, ao seu marido.- 1 Coríntios 7:3",
"Encontrei aquele a quem ama a minha alma; agarrei-me a ele e não o deixei ir. - Cantares de Salomão 3:4",
"Deleita-te no Senhor, e ele concederá os desejos do teu coração. - Salmos 37:4",
"Assim não são mais dois, mas uma só carne. Portanto, o que Deus ajuntou não o separe o homem. - Mateus 19:6",
"Como és formosa, amiga minha, como és formosa! Os teus olhos são pombas. - Cantares de Salomão 1:15",
"Amados, amemo-nos uns aos outros, porque o amor procede de Deus; e todo aquele que ama é nascido de Deus e conhece a Deus. - 1 João 4:7",
"Melhor é serem dois do que um, porque têm melhor paga do seu trabalho. - Eclesiastes 4:9",
"Como é formoso o teu amor, minha irmã, minha esposa! Quanto melhor é o teu amor do que o vinho! - Cantares de Salomão 4:10",
"Maridos, ame cada um a sua esposa, assim como Cristo amou a igreja e entregou-se por ela. - Efésios 5:25",
"Por isso, deixará o homem pai e mãe e se unirá à sua mulher, e eles se tornarão uma só carne. - Gênesis 2:24",
"Agora, pois, permanecem a fé, a esperança e o amor, estes três; mas o maior destes é o amor. - 1 Coríntios 13:13",
"Mulher virtuosa, quem a achará? O seu valor muito excede ao de rubis. - Provérbios 31:10",
"O homem que acha uma esposa acha o bem e alcança a benevolência do Senhor. - Provérbios 18:22",
"Como tu és formosa, amiga minha, como tu és formosa! Os teus olhos são como pombas. - Cantares de Salomão 1:15",
"Quem encontra uma esposa encontra algo excelente; recebeu uma bênção do Senhor. - Provérbios 18:22",
"Deus é amor, e aquele que permanece no amor permanece em Deus, e Deus, nele. - 1 João 4:16",
"O amor cubra todos os pecados. - 1 Pedro 4:8",
"Mas, se não temos amor, nada somos. - 1 Coríntios 13:2",
"Como maçãs de ouro em salvas de prata, assim é a palavra dita a seu tempo. - Provérbios 25:11",
"Muitas águas não podem apagar o amor, nem os rios afogá-lo. - Cantares de Salomão 8:7",
"Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração. - Salmos 37:4",
"Que me beije com os beijos da sua boca! Porque melhor é o seu amor do que o vinho. - Cantares de Salomão 1:2",
"Portanto, cada um de vocês também ame a sua mulher como a si mesmo, e a mulher trate o marido com todo o respeito. - Efésios 5:33",
"Alegre-se com a esposa da sua juventude. - Provérbios 5:18",
"Um ao outro ajudou e ao seu companheiro disse: Sê forte. - Isaías 41:6",
"Não se turbe o vosso coração; credes em Deus, crede também em mim. - João 14:1",
"Acima de tudo, porém, revistam-se do amor, que é o elo perfeito. - Colossenses 3:14",
"Como é agradável o teu amor, minha irmã, minha noiva! Como é melhor o teu amor do que o vinho! - Cantares de Salomão 4:10",
"Põe-me como selo sobre o teu coração, como selo sobre o teu braço; porque o amor é forte como a morte. - Cantares de Salomão 8:6",
"O coração alegre aformoseia o rosto; mas pela dor do coração o espírito se abate. - Provérbios 15:13",
"E o Senhor Deus disse: Não é bom que o homem esteja só; far-lhe-ei uma ajudadora idônea para ele. - Gênesis 2:18",
"O marido pague à mulher o que lhe é devido, e da mesma sorte a mulher, ao marido. - 1 Coríntios 7:3",
"Honroso seja entre todos o matrimônio e o leito sem mácula.- Hebreus 13:4",
"Eu sou do meu amado, e o meu amado é meu. - Cantares de Salomão 6:3",
"Assim também os maridos devem amar a sua mulher como ao próprio corpo. Quem ama a esposa a si mesmo se ama. - Efésios 5:28",
"Seduziste-me, Senhor, e eu fui seduzido; mais forte foste do que eu e prevaleceste. - Jeremias 20:7",
"Dá cerveja ao que está prestes a perecer e vinho aos amargurados de alma. - Provérbios 31:6",
"O coração alegre serve de bom remédio, mas o espírito abatido seca os ossos. - Provérbios 17:22",
"O Senhor é bom para com todos; tem compaixão de todas as suas criaturas. - Salmos 145:9",
"Suave é o amor, e agradável é a amizade; mas, mais do que ambas, é o benefício do amigo. - Eclesiástico 6:5",
"Quem encontrou uma esposa fiel encontrou a felicidade. - Provérbios 31:10",
"Amarás o Senhor, teu Deus, de todo o teu coração, de toda a tua alma e de todo o teu entendimento. - Mateus 22:37",
"Deus é amor. Quem permanece no amor, permanece em Deus, e Deus, nele. - 1 João 4:16",
"Tudo posso naquele que me fortalece. - Filipenses 4:13",
"Melhor é serem dois do que um, porque têm melhor recompensa do seu trabalho. - Eclesiastes 4:9",
"Dêem graças ao Senhor, porque ele é bom. O seu amor dura para sempre. - Salmos 136:1",
"Havendo amor fraternal, sejam terna misericórdia e humildade. - Romanos 12:10",
"Amem-se uns aos outros com amor fraternal. Prefiram dar honra aos outros mais do que a vocês. - Romanos 12:10",
  ];

  var indice = Math.floor(Math.random() * mensagensAmor.length);
  var mensagem = mensagensAmor[indice];

  mensagemEl.textContent = mensagem;
}

btnEl.addEventListener("click", getLove);
